# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'smartParking.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color:rgb(222, 217, 133);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.onButton = QtWidgets.QPushButton(self.centralwidget)
        self.onButton.setGeometry(QtCore.QRect(20, 350, 131, 51))
        self.onButton.setStyleSheet("color:rgb(238, 238, 236);\n"
"background-color:rgb(239, 41, 41);")
        self.onButton.setObjectName("onButton")
        self.offButton = QtWidgets.QPushButton(self.centralwidget)
        self.offButton.setGeometry(QtCore.QRect(20, 430, 131, 51))
        self.offButton.setStyleSheet("color:rgb(238, 238, 236);\n"
"background-color:rgb(115, 210, 22);\n"
"")
        self.offButton.setObjectName("offButton")
        self.spotOne = QtWidgets.QLCDNumber(self.centralwidget)
        self.spotOne.setGeometry(QtCore.QRect(50, 60, 81, 111))
        self.spotOne.setStyleSheet("background-color:rgb(138, 226, 52);\n"
"textcolor:rgb(0, 0, 0);")
        self.spotOne.setObjectName("spotOne")
        self.spotTwo = QtWidgets.QLCDNumber(self.centralwidget)
        self.spotTwo.setGeometry(QtCore.QRect(150, 60, 81, 111))
        self.spotTwo.setStyleSheet("background-color:rgb(138, 226, 52);\n"
"textcolor:rgb(0, 0, 0);")
        self.spotTwo.setObjectName("spotTwo")
        self.spotThree = QtWidgets.QLCDNumber(self.centralwidget)
        self.spotThree.setGeometry(QtCore.QRect(250, 60, 81, 111))
        self.spotThree.setStyleSheet("background-color:rgb(138, 226, 52);\n"
"textcolor:rgb(0, 0, 0);")
        self.spotThree.setObjectName("spotThree")
        self.spotFour = QtWidgets.QLCDNumber(self.centralwidget)
        self.spotFour.setGeometry(QtCore.QRect(350, 60, 81, 111))
        self.spotFour.setStyleSheet("background-color:rgb(138, 226, 52);\n"
"textcolor:rgb(0, 0, 0);")
        self.spotFour.setObjectName("spotFour")
        self.spotFive = QtWidgets.QLCDNumber(self.centralwidget)
        self.spotFive.setGeometry(QtCore.QRect(450, 60, 81, 111))
        self.spotFive.setStyleSheet("background-color:rgb(138, 226, 52);\n"
"textcolor:rgb(0, 0, 0);")
        self.spotFive.setObjectName("spotFive")
        self.warningLight = QtWidgets.QFrame(self.centralwidget)
        self.warningLight.setGeometry(QtCore.QRect(20, 230, 120, 80))
        self.warningLight.setStyleSheet("background-color: rgb(164, 0, 0);")
        self.warningLight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.warningLight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.warningLight.setObjectName("warningLight")
        self.PAText = QtWidgets.QTextEdit(self.centralwidget)
        self.PAText.setGeometry(QtCore.QRect(180, 220, 341, 271))
        self.PAText.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border: 2px solid black;")
        self.PAText.setObjectName("PAText")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(180, 500, 341, 41))
        self.sendButton.setStyleSheet("background-color:rgb(186, 189, 182);")
        self.sendButton.setObjectName("sendButton")
        self.sensorText = QtWidgets.QLabel(self.centralwidget)
        self.sensorText.setGeometry(QtCore.QRect(580, 220, 181, 271))
        self.sensorText.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border: 2px solid black;")
        self.sensorText.setObjectName("sensorText")
        self.titleText = QtWidgets.QTextEdit(self.centralwidget)
        self.titleText.setGeometry(QtCore.QRect(600, 510, 141, 41))
        self.titleText.setStyleSheet("background-color:rgb(186, 189, 182);\n"
"color:rgb(0, 0, 0)")
        self.titleText.setObjectName("titleText")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 30, 63, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 30, 63, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 30, 63, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(370, 30, 63, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(470, 30, 63, 20))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.onButton.setText(_translate("MainWindow", "Warn On"))
        self.offButton.setText(_translate("MainWindow", "Warn Off"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
        self.titleText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; vertical-align:super;\">Sensor Data:</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Lot 1"))
        self.label_2.setText(_translate("MainWindow", "Lot 2"))
        self.label_3.setText(_translate("MainWindow", "Lot 3"))
        self.label_4.setText(_translate("MainWindow", "Lot 4"))
        self.label_5.setText(_translate("MainWindow", "Lot 5"))